# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install build tools
RUN apk add --no-cache python3 make g++

WORKDIR /app

# Copy package and tsconfig
COPY package.json pnpm-lock.yaml tsconfig.json ./

# Copy source
COPY src ./src

# Copy recorder
COPY src/recorder ./src/recorder

# Install dependencies without running scripts, then install build deps and compile
RUN pnpm install --ignore-scripts && \
  pnpm install typescript @types/node --no-save --no-package-lock && \
  npx run build

# Remove dev dependencies
RUN npm prune --production

# Expose port
ENV PORT=3000

# Default command to run the MCP server
ENTRYPOINT ["node", "build/index.js"]