# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM oven/bun:alpine

# Create app directory
WORKDIR /app

# Copy project files
COPY package.json bun.lock tsconfig.json eslint.config.js prettier.config.mjs ./
COPY src ./src

# Install dependencies
RUN bun install

# Build with bun
RUN bun build src/index.ts --outdir build --target node \
    && chmod +x build/*.js \
    && cp -r src/recorder build/ \
    && cp node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs build/

# Default command
ENTRYPOINT ["node", "build/index.js"]
