# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install build tools
RUN apk add --no-cache python3 make g++

WORKDIR /app

# Copy package and tsconfig
COPY package.json pnpm-lock.yaml tsconfig.json ./

# Copy source
COPY src ./src

# Install deps and build
RUN pnpm store prune
RUN pnpm install --frozen-lockfile && pnpm run build:http

# Remove dev dependencies
RUN npm prune --production

# Expose port
ENV PORT=3000

# Default command to run the MCP server
ENTRYPOINT ["node", "build/http-server.js"]